### PR TITLE
Expand mypy.bzl to be bazel cacheable.

### PR DESCRIPTION
**Pull request by dshahbaz**
This change does 3 things:

* Propagate mypy cached metadata to dependents. Mypy generates cache
  data for every module it parses in the form of a pair of json files.
  Before this change, these files were dropped as soon as they were
  generated, so that each mypy analysis for each py_* target had to
  reparse/regenerate the metadata for all transitive sources. This
  change propagates these cached metadata files to dependents (similar
  to how the mypy docs recommend caching for speeding up mypy runs).

* Propagate typeshed stdlib cached metadata to dependents. Similar to
  the above for py_* targets, mypy also is able to cache the metadata it
  generates for typeshed stubs. This is highly cacheable, since the
  typeshed stubs never change, and represent the majority of imports
  from python sources.

* Use mypy's `--module` arguments for finding modules. Before, all
  sources were passed to `mypy` as source paths on the command line.
  However, this causes issues when the *module path* of a source file
  does not match the *source path* of a file. The module path might
  differ if a py_library target has an `imports` attribute, meaning that
  the module can be imported relative to the paths in `imports`. By
  instead using repeated `-m` arguments, this change modifies this
  behavior, so that module paths always match source paths. This is not
  just a cosmetic change, though, because the cachability of the mypy
  metadata *depends on the module path* being correct (matching how the
  py_library is actually imported by dependents).

### CODE REVIEW

**Comment by dshahbaz** [comment]
Hi @thundergolfer , I realize this is a big PR, but I've captured the design goals here:

https://github.com/dshahbaz/bazel-mypy-integration/wiki 

ptal at that doc first. thank you!

**Comment by thundergolfer** [comment]
Impressive looking contribution. I could take me a little while to review it all, but thanks in advance! I'll start with that doc.

**Comment by dshahbaz** [comment]
FYI, this change is outdated. With mypy 0.800, there are additional options available to make `py_library` targets with import paths more sane (`--explicit-package-bases` https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules). The PR here is an older state of work I've done internally.

**Comment by thundergolfer** [comment]
Thanks for the update 👍

**Pull request closed without merging**
